DROP DATABASE if exists APIWithSecurity; 

CREATE DATABASE APIWithSecurity;

USE APIWithSecurity;

CREATE TABLE USER(
    EMAIL VARCHAR(40) NOT NULL UNIQUE,
    PASSWORD VARCHAR(60) NOT NULL,
    NAME VARCHAR(30) NOT NULL,
    MOBILE VARCHAR(10) NOT NULL UNIQUE,
    ENABLED BOOLEAN DEFAULT 1,
    ROLE VARCHAR(20) NOT NULL,
    PIN VARCHAR(60) NOT NULL,
    OTP INTEGER(6) NULL,
    OTP_TIME DATETIME NULL,
    PRIMARY KEY (EMAIL)
);

CREATE TABLE RETAILER(
    EMAIL VARCHAR(40) NOT NULL UNIQUE,
    AADHAAR INTEGER(12) NOT NULL,
    PAN VARCHAR(10) NOT NULL,
	GST VARCHAR(15),
    SHOP_NAME VARCHAR(30) NOT NULL,
    SHOP_ADDRESS VARCHAR(50) NOT NULL,
    SHOP_PINCODE INTEGER(6) NOT NULL,
    SHOP_CITY VARCHAR(20) NOT NULL,
    SHOP_STATE VARCHAR(30) NOT NULL,
    VERIFIED BOOLEAN DEFAULT 0,
	PRIMARY KEY (EMAIL)	
);

CREATE TABLE INVALID_TOKENS(
    ID INTEGER NOT NULL AUTO_INCREMENT,
    TOKEN 

);
